### ISSUE TITLE
A bit complicated router usage. Can you please explain why this set of routers was chosen ?

### ISSUE THREAD

**Issue by alex-Z-** [MarkBezrukaviy/React-test-task-front#3]
https://github.com/MarkBezrukaviy/React-test-task-front/blob/9e33f52338a17f9a3fb27bc9a9a094d7ed825ea2/src/js/containers/App.js#L9

**Comment by MarkBezrukaviy** [comment]
Because I have a server, and the BrowserRouter should be used when there is a server.
